version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: finrisk_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: finrisk
    ports:
      - "5432:5432"

  dashboard:
    build: .
    container_name: finrisk_dashboard
    ports:
      - "8501:8501"
    depends_on:
      - postgres

  api:
    build: .
    container_name: finrisk_api
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres
